'use strict';
const assert=require('assert');
const {initialState,legalTargets,validateAndApply,WHITE,BLACK,countPieces}=require('../checkers');
let s=initialState();
assert.equal(countPieces(s.board,WHITE),12);
assert.equal(countPieces(s.board,BLACK),12);
assert.equal(s.turn,WHITE);
assert.equal(s.status,'playing');
assert(legalTargets(s,WHITE).length>0,'Brancas sem jogadas iniciais.');
const first=legalTargets(s,WHITE)[0];
const moved=validateAndApply(s,first.from,first.to);
assert(moved.ok,'Primeira jogada válida foi rejeitada.');
assert.equal(moved.state.turn,BLACK);
assert.equal(moved.state.moves,1);
const bad=validateAndApply(moved.state,{r:7,c:0},{r:6,c:1});
assert.equal(bad.ok,false);
// forced capture scenario
const forced={board:Array.from({length:8},()=>Array(8).fill(0)),turn:WHITE,winner:null,draw:false,status:'playing',moves:0,halfMoves:0,mustContinue:null};
forced.board[5][0]={color:WHITE,king:false};
forced.board[4][1]={color:BLACK,king:false};
const targets=legalTargets(forced,WHITE);
assert.equal(targets.length,1);
assert.deepEqual(targets[0].to,{r:3,c:2});
const cap=validateAndApply(forced,targets[0].from,targets[0].to);
assert(cap.ok&&cap.move.capture,'Captura obrigatória não aplicada.');
console.log('CHECKERS SMOKE 2.9.1 PASSED');
